name: Build

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    paths-ignore:
      - '**.md'
    branches:
      - master
    tags:
      - v**

jobs:
  tag_main:
    runs-on: ubuntu-latest
    steps:
      - uses: us-ignite/semver-action@main
        with:
          is_main: 'true'
          is_release: 'false'

  self-test:
    name: Run self-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          owner: ${{ github.repository_owner }}
          repo: trigger-workflow-and-wait
          ref: ${{ github.event.repository.default_branch || 'master' }}
          github_token: ${{ secrets.US_IGNITE_ACTIONS_DISPATCH_PAT }}
          workflow_file_name: selftest.yaml
          client_payload: '{"test": "true"}'
          wait_interval: 11
          trigger_workflow: true
          wait_workflow: true
          propagate_failure: true
